# Generated by Django 5.2.5 on 2025-08-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtelierViewPermission',
        ),
    ]
