# Generated by Django 5.2.5 on 2025-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0002_heardaboutusoption_institutiontypeoption_and_more"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="atelier",
        ),
        migrations.AddField(
            model_name="task",
            name="ateliers",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="customuser.atelier"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="for_all_ateliers",
            field=models.BooleanField(default=False),
        ),
    ]
