# Generated by Django 5.2.5 on 2025-08-23 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0002_alter_commission_options"),
        ("tasks", "0002_delete_atelierviewpermission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Görev", "verbose_name_plural": "Görevler"},
        ),
        migrations.AlterModelOptions(
            name="taskrolepermission",
            options={
                "verbose_name": "Görev İzin Kuralı",
                "verbose_name_plural": "Görev İzin Kuralları",
            },
        ),
        migrations.CreateModel(
            name="AtelierViewPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atelier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customuser.atelier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "atelier")},
            },
        ),
    ]
