# Generated by Django 5.2.5 on 2025-08-27 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0002_alter_commission_options"),
        ("tasks", "0004_alter_task_options_alter_taskrolepermission_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Görev", "verbose_name_plural": "Görevler"},
        ),
        migrations.RemoveField(
            model_name="task",
            name="ateliers",
        ),
        migrations.CreateModel(
            name="TaskAtelier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "atelier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="customuser.atelier",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atelier_completed_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "unique_together": {("task", "atelier")},
            },
        ),
        migrations.AddField(
            model_name="task",
            name="atelier",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks",
                through="tasks.TaskAtelier",
                to="customuser.atelier",
            ),
        ),
        migrations.DeleteModel(
            name="AtelierViewPermission",
        ),
    ]
