# Generated by Django 5.2.4 on 2025-08-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
