# Generated by Django 5.2.5 on 2025-08-23 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commission",
            options={"verbose_name": "Komisyon", "verbose_name_plural": "Komisyonlar"},
        ),
    ]
