# Generated by Django 5.2.5 on 2025-08-16 10:27

import customuser.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeardAboutUsOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Ad"),
                ),
                (
                    "is_builtin",
                    models.BooleanField(default=False, verbose_name="Yerleşik"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Kaynak (Bizden Nasıl Haberdar)",
                "verbose_name_plural": "Kaynaklar (Bizden Nasıl Haberdar)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionTypeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Ad"),
                ),
                (
                    "is_builtin",
                    models.BooleanField(default=False, verbose_name="Yerleşik"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Kurum Tipi",
                "verbose_name_plural": "Kurum Tipleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NationalityOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="Ad"),
                ),
                (
                    "is_builtin",
                    models.BooleanField(default=False, verbose_name="Yerleşik"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Uyruk",
                "verbose_name_plural": "Uyruklar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Örn: superadmin, admin, instructor, student",
                        unique=True,
                        verbose_name="Kod",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="1=En yüksek, 99=En düşük", verbose_name="Seviye"
                    ),
                ),
                (
                    "is_builtin",
                    models.BooleanField(default=False, verbose_name="Yerleşik"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roller",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolTypeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Ad"),
                ),
                (
                    "is_builtin",
                    models.BooleanField(default=False, verbose_name="Yerleşik"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Okul Tipi",
                "verbose_name_plural": "Okul Tipleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StatusOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Ad"),
                ),
                (
                    "is_builtin",
                    models.BooleanField(default=False, verbose_name="Yerleşik"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Aktiflik Durumu",
                "verbose_name_plural": "Aktiflik Durumları",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="atelier",
            name="address",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Konum"
            ),
        ),
        migrations.AddField(
            model_name="atelier",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
        migrations.AddField(
            model_name="atelier",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="atelier",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Telefon",
            ),
        ),
        migrations.AddField(
            model_name="atelier",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__code": "workshop_responsible"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_ateliers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sorumlu",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adres"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="classroom",
            field=models.CharField(
                blank=True,
                help_text="Örn: 10, 3. sınıf, 1. sınıf",
                max_length=50,
                null=True,
                verbose_name="Sınıf",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="continuing_institution",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Devam Ettiği Kurum"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="current_institution_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="İçerisinde Bulunduğunuz Kurum Adı",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Bölüm"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="disability_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Engel Açıklaması"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="İlçe"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "İlkokul"),
                    ("middle", "Ortaokul"),
                    ("high", "Lise"),
                    ("associate", "Ön Lisans"),
                    ("bachelor", "Lisans"),
                    ("master", "Yüksek Lisans"),
                    ("phd", "Doktora"),
                    ("other", "Diğer"),
                ],
                max_length=20,
                null=True,
                verbose_name="Eğitim Seviyesi",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="expected_graduation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Beklenen Mezuniyet Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="faculty_institute",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Fakülte / Enstitü"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Erkek"),
                    ("female", "Kadın"),
                    ("na", "Belirtmek İstemiyorum"),
                ],
                max_length=10,
                null=True,
                verbose_name="Cinsiyet",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_disability",
            field=models.BooleanField(default=False, verbose_name="Engeli Var Mı?"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_graduate",
            field=models.BooleanField(
                default=False,
                help_text="Mezun seviyesindeysen, en son tamamlanan eğitim bilgilerini beyan et.",
                verbose_name="Mezunum",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_completed_department",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="En Son Tamamlanan Bölüm",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_completed_education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "İlkokul"),
                    ("middle", "Ortaokul"),
                    ("high", "Lise"),
                    ("associate", "Ön Lisans"),
                    ("bachelor", "Lisans"),
                    ("master", "Yüksek Lisans"),
                    ("phd", "Doktora"),
                    ("other", "Diğer"),
                ],
                max_length=20,
                null=True,
                verbose_name="En Son Tamamlanan Eğitim Seviyesi",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_completed_faculty_institute",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="En Son Tamamlanan Fakülte / Enstitü",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_completed_graduation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="En Son Tamamlanan Mezuniyet Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_completed_school",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="En Son Tamamlanan Okul",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="passport_number",
            field=models.CharField(
                blank=True,
                help_text="Sadece harf/rakam",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{5,20}$",
                        message="Pasaport numarası 5-20 karakter, harf/rakam olmalıdır.",
                    )
                ],
                verbose_name="Pasaport Numarası",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profession",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Meslek"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="school_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Okul"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Şehir"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ülke"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=75, verbose_name="Ad"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=75, verbose_name="Soyad"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="permission_level",
            field=models.PositiveSmallIntegerField(
                default=99, help_text="1=En yüksek yetki"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=customuser.models.user_profile_upload_path,
                verbose_name="Profil Fotoğrafı",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="heard_about_us",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customuser.heardaboutusoption",
                verbose_name="Bizden Nasıl Haberdar Oldunuz?",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="current_institution_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customuser.institutiontypeoption",
                verbose_name="İçerisinde Bulunduğunuz Kurum Tipi",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customuser.nationalityoption",
                verbose_name="Uyruk",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="customuser.role",
                verbose_name="Rol",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="school_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customuser.schooltypeoption",
                verbose_name="Okul Tipi",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customuser.statusoption",
                verbose_name="Aktiflik Durumu",
            ),
        ),
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role__code": "student_parent"},
                        related_name="ward_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Veliler",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role__code": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci - Veli İlişkisi",
                "verbose_name_plural": "Öğrenci - Veli İlişkileri",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student",), name="unique_student_in_parent_link"
                    )
                ],
            },
        ),
    ]
