# Generated by Django 5.2.5 on 2025-08-21 13:42

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Başlık')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Metin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arşivlendi mi?')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=10, verbose_name='Öncelik')),
                ('private_note_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Özel Not Başlığı')),
                ('private_note_body', models.TextField(blank=True, null=True, verbose_name='Özel Not İçeriği')),
                ('publication_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Yayınlanma Tarihi')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Zamanı')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'permissions': (('deactivate_announcement', 'Duyuruyu pasife alma izni'),),
            },
        ),
        migrations.CreateModel(
            name='AnnouncementArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=True, verbose_name='Arşivlendi mi?')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Arşivlenme Zamanı')),
            ],
            options={
                'verbose_name': 'Duyuru Arşiv Kaydı',
                'verbose_name_plural': 'Duyuru Arşiv Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Duyuru İzin Kuralı',
                'verbose_name_plural': 'Duyuru İzin Kuralları',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=True, verbose_name='Okundu mu?')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Okunma Zamanı')),
            ],
            options={
                'verbose_name': 'Duyuru Okunma Kaydı',
                'verbose_name_plural': 'Duyuru Okunma Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='ExtraAtelierAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Zamanı')),
            ],
            options={
                'verbose_name': 'Ek Atölye Yetkisi',
                'verbose_name_plural': 'Ek Atölye Yetkileri',
            },
        ),
    ]
