# Generated by Django 5.2.5 on 2025-08-21 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('customuser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='ateliers',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='customuser.atelier', verbose_name='Atölyeler'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='customuser.commission', verbose_name='Komisyon'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='announcementarchive',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='announcements.announcement', verbose_name='Duyuru'),
        ),
        migrations.AddField(
            model_name='announcementarchive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_archives', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='announcementpermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_permissions', to='customuser.role'),
        ),
        migrations.AddField(
            model_name='announcementread',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='announcements.announcement', verbose_name='Duyuru'),
        ),
        migrations.AddField(
            model_name='announcementread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='extraatelieraccess',
            name='ateliers',
            field=models.ManyToManyField(related_name='extra_access_users', to='customuser.atelier', verbose_name='Yetkili Olduğu Ek Atölyeler'),
        ),
        migrations.AddField(
            model_name='extraatelieraccess',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='extraatelieraccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_atelier_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddIndex(
            model_name='announcementarchive',
            index=models.Index(fields=['user', 'announcement'], name='announcemen_user_id_bb89b7_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementarchive',
            index=models.Index(fields=['announcement', 'is_archived'], name='announcemen_announc_c81204_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementarchive',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='uniq_archive_ann_user'),
        ),
        migrations.AddConstraint(
            model_name='announcementpermission',
            constraint=models.UniqueConstraint(fields=('role',), name='uq_announcement_permission_role'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['user', 'announcement'], name='announcemen_user_id_bdf288_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['announcement', 'is_read'], name='announcemen_announc_279c90_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementread',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='uniq_read_ann_user'),
        ),
        migrations.AddIndex(
            model_name='extraatelieraccess',
            index=models.Index(fields=['user', 'is_active'], name='announcemen_user_id_684ee9_idx'),
        ),
    ]
